# Generated by Django 4.0.6 on 2022-07-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0002_rename_repertoiremodel_repertoire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repertoire',
            new_name='Utilisateur',
        ),
    ]
