# Generated by Django 4.0.6 on 2022-07-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0005_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
